
/*2) features of ES6?
==>The let keyword
The const keyword
Arrow Functions
For/of
Map Objects
Set Objects
Classes
Promises
Symbol
Default Parameters
Function Rest Parameter
String.includes()
String.startsWith()
String.endsWith()
Array.from()
Array keys()
Array find()
Array findIndex()
New Math Methods
New Number Properties
New Number Methods
New Global Methods
Iterables Object.entries
JavaScript Modules
====or====
let and const Keywords
Arrow Functions
Multi-line Strings
Default Parameters
Template Literals
Destructuring Assignment
Enhanced Object Literals
Promises
Classes
Modules
3)difference between ES% and ES6?
==>Difference between ES5 and ES6
Based on	ES5	ES6
Definition   *	ES5 is the fifth edition of the ECMAScript (a trademarked scripting language specification defined by ECMA International)                        	ES6 is the sixth edition of the ECMAScript (a trademarked scripting language specification defined by ECMA International).
Release      *	It was introduced in 2009.
	        It was introduced in 2015.
Data-types   * 	ES5 supports primitive data types that are string, number, boolean, null, and undefined.	
                In ES6, there are some additions to JavaScript data types. It introduced a new primitive data type 'symbol' for supporting unique                 values.
Defining Variables   *	In ES5, we could only define the variables by using the var keyword.
	                In ES6, there are two new ways to define variables that are let and const.
Performance  *	As ES5 is prior to ES6, there is a non-presence of some features, so it has a lower performance than ES6.	
                Because of new features and the shorthand storage implementation ES6 has a higher performance than ES5.
Support      *	A wide range of communities supports it.
        	It also has a lot of community support, but it is lesser than ES5.
Object Manipulation  *	ES5 is time-consuming than ES6.
	                Due to destructuring and speed operators, object manipulation can be processed more smoothly in ES6.
Arrow Functions     *	In ES5, both function and return keywords are used to define a function.
                	An arrow function is a new feature introduced in ES6 by which we don't require the function keyword to define the function.
Loops	            *   In ES5, there is a use of for loop to iterate over elements.
                	ES6 introduced the concept of for...of loop to perform an iteration over the values of the iterable objects.


4)operators of js?
==>There are following types of operators in JavaScript.

Arithmetic Operators   [+ - * / % ++ --]
Comparison (Relational) Operators    [==  ===  != !==  >  >=  <  <=]
Bitwise Operators          [&   |   ^ ~  <<   >>   >>>
Logical Operators       [ &&    ||    !]
Assignment Operators   [=  +=  -=   *=  /=   %=  ]
Special Operators      [ (?:)   ,   delete    in    instanceof    new    typeof    yield    ]


5) what is hoisting?
==> while you declaired a varaible as 'var' and assignit before declaration then js will uplift the declaration on the top.


6) what is DOM?
==>its stands for document object model.it allows programs and scripts to dynamically access and update the content, structure, and style of a document.


7) what is array function?
==> an array is an object that can store multiple values at once.
or 
it is collection of similar data type elements.eg.[1,2,3,4,5,6]
the  type of array is also object.


8) difference between == and ===?
==>= is used for assigning values to a variable in JavaScript. == is used for comparison between two variables irrespective of the datatype of variable. === is used for comparision between two variables but this will check strict type, which means it will check datatype and compare two values.


9) what is ecma script?
==> ECMA is a short form of "European Computer Manufacturers Association Script".
The ECMAScript standard defines the rules, details, and guidelines that the scripting language must observe to be considered ECMAScript compliant. So that's ECMAScript. ... JavaScript is a general-purpose scripting language that conforms to the ECMAScript specification.


10) what is varaible ?
==> variable is an identifier or a name which is used to refer a value.

11) what are the reserved keywords in js? 
==>
var
let
const 
delete
for
void
while
else
if
public
private
try
static
do
case
in



js is asynchronous and single threded


Q. what is identifier in js?
==>An identifier is a sequence of characters in the code that identifies a variable, function, or property
const a="hello'



q. adv and disadv.of js
==>adv;
client side execution
validation on browser
easy language
Speed. Client-side JavaScript is very fast because it can be run immediately within the client-side browser. ...
Simplicity. JavaScript is relatively simple to learn and implement.
Popularity. ...

disadv:
less secure due to cleint side execution
no hardware access
Disadvantages of JavaScript
Client-side Security. Since the JavaScript code is viewable to the user, others may use it for malicious purposes. ...
Browser Support. The browser interprets JavaScript differently in different browsers. ...
Lack of Debugging Facility. ...
Single Inheritance. ...
Sluggish Bitwise Function. ...
Rendering Stopped*/